[package]
name        = "mnemesis"
version     = "0.1.0"
description = "Never forget anything ever again"
authors     = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
license     = "BSD-2-Clause"
readme      = "README.md"

[dependencies]
base32          = "^0.3"
clap            = "^2"
oath            = "^0.10"
rustc-serialize = "^0.3"
